### ISSUE TITLE
Ubuntu official repository

### ISSUE THREAD

**Issue by hezral** [kernc/xsuspender#23]
Hello, thanks for making this tool. I understand that it's available via the OpenSuse repositories but was wondering why its not in the official Ubuntu repositories? And what would it take to have it there?

**Comment by kernc** [comment]
It's available in openSUSE Build Service because I have an account and it's built there. In order to get it in Ubuntu straight, one would need to propose/request/package it either for [Debian](https://wiki.debian.org/RFP) or [Ubuntu](https://wiki.ubuntu.com/UbuntuDevelopment/NewPackages#Requesting_a_new_package_for_Ubuntu). You're welcome to do that. :smiley:

**Comment by hezral** [comment]
Thanks, i was wondering if that was the reason 😃 
I'm asking because i'm making a GUI for easy use and hit a wall since its not in the official repo and kinda breaks the ease of use that I'm trying to create. I will try to submit a request.

**Comment by kernc** [comment]
:open_mouth:

Certainly do check back when/if you make it!

**Comment by hezral** [comment]
Will do, its daunting but might be a good learning experience
