### ISSUE TITLE
debian release signature invalid 

### ISSUE THREAD

**Issue by tpo** [kernc/xsuspender#37]
Hi,

```
# apt-get update
Err:1 http://download.opensuse.org/repositories/home:/kernc:/xsuspender/Debian_Testing  InRelease
  The following signatures were invalid: EXPKEYSIG 9DCD4975404FB075 home:kernc OBS Project <home:kernc@build.opensuse.org>
```

The problem seems to be that [your key](http://download.opensuse.org/repositories/home:/kernc:/xsuspender/Debian_Testing/Release.key) is no more valid:

```
$ apt-key list
/etc/apt/trusted.gpg.d/home_kernc_xsuspender.gpg
------------------------------------------------
pub   rsa2048 2017-12-30 [SC] [expired: 2022-05-05]
      550F F6DE 820F 0396 BC69  9C26 9DCD 4975 404F B075
uid           [ expired] home:kernc OBS Project <home:kernc@build.opensuse.org>
```

**Comment by kernc** [comment]
Not sure about Debian Testing, since [its build is marked unresolvable](https://build.opensuse.org/project/show/home:kernc:xsuspender) with:

> have choice for libjpeg-dev needed by libgdk-pixbuf-2.0-dev: libjpeg-dev libjpeg62-turbo-dev,
> have choice for libjpeg-dev needed by libtiff-dev: libjpeg-dev libjpeg62-turbo-dev

and I'm not quite sure how to fix it. Any help / clues appreciated. :sweat_smile:

But published releases for other platforms have been rebuilt and should contain an updated, valid release key.

**Comment by tpo** [comment]
Hi @kernc - I do not understand how you configure the Open Build Service how to build your package. However I think that the problem that you encounter is described and a solution suggested here: https://foursixnine.io/blog/2019/01/21/Open-Build-Service-Contributing-on-a-project.html - search for "have a choice for".

?

**Comment by kernc** [comment]
The thing is, I use a [debian package tar](https://build.opensuse.org/package/show/home:kernc:xsuspender/xsuspender) to build, and since Xsuspender doesn't at all depend on libjpeg-dev, I shouldn't need to specify any of those alternatives. I think it's a bug of OBS, which should try to resolve ambiguations in a headless manner.

This is basically bug https://github.com/openSUSE/open-build-service/issues/10773.

**Comment by kernc** [comment]
Resolved with https://github.com/openSUSE/open-build-service/issues/10773#issuecomment-1310197192.

Thanks for the help!
